version: '2'
services:
  servicedesk-app:
    image: servicedesk
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://servicedesk-postgresql:5432/servicedesk
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  servicedesk-postgresql:
    extends:
      file: postgresql.yml
      service: servicedesk-postgresql
